### PR TITLE
Fix type signature of HttpLatencyMonitoringFilter

### PR DESCRIPTION
**Pull request by hderms**
I think this was closer to what was intended and believe the current implementation was a typo

### CODE REVIEW

**Comment by samstarling** [comment]
Hi @hderms – thanks for this, you're right. One problem though: the code isn't compiling because `ServiceLabeller` takes type parameters: it needs to be `ServiceLabeller[Request, Response]`.

**Comment by hderms** [comment]
@samstarling my bad I didn't actually fire up the IDE for this one. I'll fix and push

**Comment by hderms** [comment]
also @samstarling thanks so much for doing this. I think the design is pretty good and it's provided immense value for me trying to get started with Prometheus monitoring

**Comment by samstarling** [comment]
@hderms No problem: I haven't done much work on this repository lately, so it's a little unloved – but I'm glad you're finding it useful. Let me know if you ever have ideas for features, or if you need a hand with the PR at all.

**Comment by hderms** [comment]
@samstarling the only thing I could use help with is understanding why 2 of the builds succeed and 2 fail.

**Comment by samstarling** [comment]
@hderms That looks like a JDK7/Travis problem, rather than anything you've done: let me see if I can figure that out tonight: JDK7 is pretty old now.

**Pull request merged**
