### PR TITLE
Add Scala 2.13

### LINKED ISSUE #48: Cross-build for scala 2.13
Finagle has made an effort to make all their modules available for Scala 2.13. 

it would be great if this dependency is cross-build for 2.12 and 2.13.

### PR DESCRIPTION
**Pull request by DieBauer**
This adds cross compilation for scala 2.13. 

It builds on the work done by #47 

Closes #48

### CODE REVIEW

**Comment by samstarling** [comment]
Hey @DieBauer – thanks for the contribution, and I'm sorry it took me a few days to get around to reviewing this.

**Comment by DieBauer** [comment]
Thanks for looking into this, and accepting the PR. And awesome that you got the release out :)

**Comment by DieBauer** [comment]
@samstarling I noticed this release got published to Bintray, and it is not available in maven central. https://search.maven.org/artifact/com.samstarling/finagle-prometheus_2.13 is that intentional?

**Comment by samstarling** [comment]
@DieBauer Sorry for the delay (again!) – I missed off this manual step of syncing to Maven Central, but I just started the process on Bintray. Let me know if it's not showing up for you within a couple of hours or so.

**Pull request merged**
